### ISSUE TITLE
While trying to resolve module `immer@10.0.2` React Native 

### ISSUE THREAD

**Issue by nhchuongchkst19** [immerjs/immer#1058]
Error: While trying to resolve module `immer` from file `/app/screens/comment.tsx`, the package `/build/node_modules/immer/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/immer/dist/immer.mjs`. Indeed, none of these files exist

_Originally posted by @nhchuongchkst19 in https://github.com/immerjs/immer/issues/331#issuecomment-1654965627_

**Comment by mweststrate** [comment]
The package.json's main file points to `"./dist/cjs/index.js"` at https://unpkg.com/immer@10.0.2/package.json which does exist, https://unpkg.com/immer@10.0.2/dist/cjs/index.js. So this sounds rather like an issue in your build setup or React Native? The `react-native` config indeed specifies dist/immer.mjs, but again, that file exists: https://unpkg.com/immer@10.0.2/dist/immer.mjs.

cc @markerikson did you get similar reports for Redux, since we follow basically the same module config?

**Comment by markerikson** [comment]
None of our changes are officially released yet :)  They're all still in beta.

Unfortunately I don't use RN myself, so I don't have an easy way to repro / check on this.

**Comment by mweststrate** [comment]
Possible solution is mentioned here: https://github.com/immerjs/immer/issues/1065#issuecomment-1709508198

**Comment by mweststrate** [comment]
I *think* immer@10.0.3-beta solves it for everyone. Would someone mind verifying? Then I'll cut an official release.

**Comment by dmotz** [comment]
@mweststrate I tried 10.0.3-beta in a React Native app that wasn't working with previous 10.x versions, and can confirm 10.0.3-beta fixes the issue 👍
