### ISSUE TITLE
support property produce hook

### ISSUE THREAD

**Issue by millievn** [immerjs/immer#1136]
immer use `Reflect.ownKeys` to loop all property and developer cannot do anything. can we support hooks during property and value edit?

https://github.com/immerjs/immer/blob/e2d222bd4fb26abded04075c936290715e9ee335/src/utils/common.ts#L75

for example:
```js

const child = {
id: 1,
name:"1",
children: null
}

const parentNode = {
id: 1,
name:"1",
children: [child],
_parent: null
}

child._parent = parentNode
```
 
when produce next state, `_parent`  cause circle refer problem and throw error.

i know immer have the rule `Immer only supports unidirectional trees` but can we do like this?

```js

function user_defined_iter(key, value, obj, basic_iter){
  if(key === '_parent'){
    obj[key] = value
  }else {
    basic_iter(key, obj[key], obj)
 }
}

Reflect.ownKeys(obj).forEach(key => {
 user_defined_iter(key, obj[key], obj), iter)
})
```

current temporary way is to loop all nodes but if the tree is too large add deep, it may cause another performance error.

**Comment by mweststrate** [comment]
Precise semantics of iteration are defined here: https://immerjs.github.io/immer/complex-objects#semantics-in-detail. 

There is good reasons why things must be a tree; otherwise you will get really weird behavior if you change parentNode, which then wouldn't be reflected in `child._parent` (you'd just have two different parents in the same tree, and `parent === parent.children[0]._parent` would yield `false`, because Immer doesn't magically know that that pointer must be swapped!). 

Instead, just store only the parent's `id` for example on the child, so that you can always look it back up. 

But if you really must, you can probably hack around it with a getter, and either private properties or an external (weak)map to keep track of the parent refs.
