### ISSUE TITLE
typescript documentation: produce's draft callback function return type

### ISSUE THREAD

**Issue by jaimefps** [immerjs/immer#394]
## 🚀 Feature Proposal
Request: some documentation around immer & typescript.

When using typescript and Immer, I get this warning for the draft callback function:
`warning Missing return type on function  @typescript-eslint/explicit-function-return-type`

## Motivation
Typescript is very popular, so I imagine this will be an issue for a lot of new comers to Immer.

## Example
I'm not sure this is what you guys would recommend, 
but I'm doing something like the following with typescript:

```
export interface StateShape {
  myValue: MyValueType;
}

export const initialState: StateShape = {
  myValue: null
};

const reducer: Reducer<StateShape, Actions> = (
  state = initialState as StateShape,
  action: Actions
): StateShape =>
  produce(
    state,
    (draft): void | StateShape => {
      switch (action.type) {
        case "RESET":
          return initialState;
          break;

        case "SET_VALUE":
          draft.myValue = action.payload.myValue;
          break;
        // no default
      }
    }
  );
```

Since there are cases where I need to reset state, and want to return `initialState`,
this seems like my only solution; i.e., 

`(draft): void | StateShape => { ... }`

Agree, disagree? Can you add some documentation around basic typescript use cases with immer? Thanks for the awesome library!!

**Comment by mweststrate** [comment]
The problem you are having is with eslint, not with typescript (and imho this is quite an awkward rule to enforce everywhere). The return type purely depends on what you are returning from the function, so we can't state anything general about it? Like "The return type of the recipe should match what you return from the recipe function (duh). Typically `void` or `void | TheStateType` should do". 

However, it is for typescript completely unnecessary to provide this type, since that is what TS inferred already to be the signature of the recipe function anyway. So adding that annotation is really just ESLint hugging, but doesn't catch anything which wouldn't have been caught otherwise.

That being said, I think your solution is the correct way of making eslint happy :)
