### ISSUE TITLE
Suggestion for feature `hasDraft`

### ISSUE THREAD

**Issue by fwh1990** [immerjs/immer#398]
## 🚀 Feature Proposal

Can you provider new api to validate whether immer type is in deep object.

## Motivation

`hasDraft()`

## Example
```javascript

const data = {  a: 0, b: {  test: 1  } };

const draft = createDraft(data);

const foo = {
    c: 2,
    bar: draft.b,
};

// Sometimes, I don't know when user will assign immer type data to normal object.
return hasDraft(foo) ? finishDraft(createDraft(foo)) : foo;
```

**Comment by fwh1990** [comment]
Or I want to invoke method `finishDraft`, no matter how deep the immer type is, even if the top of object  is not immer type.

**Comment by fwh1990** [comment]
Or another method name `clearDraft()`

**Comment by mweststrate** [comment]
This feature looks far to specific to be part of the standard api. However, you can easily define this in your own code by leveraging some utility that walks the tree using `isDraft`. 

I'm not sure what the context of the original problem is, but I suggest to be a bit more explicit about where you have drafts and where not, rather than mixing and maxing them freely, and then needing some magic utilties that straightens it all out :). 

You should never leak drafts anywhere, or assign them to anything. They are only valid _during_ your produce function. Using them anywhere outside is just very confusing without really giving any unique benefits

**Comment by fwh1990** [comment]
Sometimes, I have to do that. Even if I find  immer type from deep object by using `isDraft`, but I can't use `finishDraft` due to it may be not top level object from `createDraft`.

**Comment by mweststrate** [comment]
As said, you shouldn't be storing your drafts anywhere, but only finalized
states, in which case you wouldn't have this problem in the first place.

So as it stands, strong arguments to implement such a feature are lacking
imho. If you want to make a case you really need to store drafts to only
finish them later, feel free to do so, but please provide a lot more
context and example code in that case :).
