### ISSUE TITLE
Rebasing patches in collaborative editing

### ISSUE THREAD

**Issue by eshvedai** [immerjs/immer#410]
## 🚀 Feature Proposal

Implement a `rebase` function that transforms patches so that they can be applied to the state created by another array of patches.

Inspired by [ProseMirror rebasing logic](http://prosemirror.net/docs/guide/#transform.rebasing)

## Motivation

I am exploring the idea of using `Immer` for collaborative editing and I came across an issue with rebasing patches on top of each other.

Imagine two collaborative editing clients (`A` and `B`) that start from the same state, each client performs an action:
```
const [stateA, patchesA] = produceWithPatches(defaultState, actionA);
const [stateB, patchesB] = produceWithPatches(defaultState, actionB);
```

Applying patches on top of the state produced by one of the clients might lead to dropping the change:
```
const stateAB = applyPatches(stateA, patchesB) // Error 💥
```

It would be nice to have a `rebase` mechanism that would allow doing this:
```
const patchesB2 = rebase(patchesB, patchesA);
const stateAB = applyPatches(stateA, patchesB2)
```

## Example

```
const state = {
  items: [0, 1, 2, 3, 4, 5]
};
```
```
const [stateA, patchesA] = produceWithPatches(state, draft => {
  draft.items[1] = 'A';
}); // { items: [0, 'A', 2, 3, 4, 5] }
```
```
const [stateB, patchesB] = produce(state, draft => {
  draft.items.shift();
}); // { items: [1, 2, 3, 4, 5] }
```
```
const stateAB = applyPatches(stateB, patchesA); // { items: [1, 'A', 3, 4, 5] }
```
where `patchesA` path is still pointing to index 1, whereas now it's a completely different item.

My desired result would be: `{ items: ['A', 2, 3, 4, 5] }`, where rebasing would update the paths of `patchesA` to point to the previous index of the `items` array, because `stateB` removed the first item.

I would appreciate any recommendations you might have regarding how to achieve this.

**Comment by mweststrate** [comment]
I've wrote about it a while ago: https://medium.com/@mweststrate/distributing-state-changes-using-snapshots-patches-and-actions-part-2-2f50d8363988

Beyond that, there are many ways in which one can reason about patches, but doing such things is not the goal of this library and can be implemented just as well in user-land / another library. Immer provides the raw patches, but any post processing as normalizing, minimising, compressing and rebasing go beyond the scope of this package.

**Comment by eshvedai** [comment]
Yeah, I saw that blog post, it was my starting point with this package actually. I didn't find the answer there unfortunately. It seems like replaying pending actions doesn't always preserve the right intent. 
Any tips on that? How do you deal with collab conflicts at Mendix?

**Comment by mweststrate** [comment]
That is because there is no generic solution to the problem, as it depends
on the semantics. For example a patch: "set x/y to nr Z" can mean
completely different things based on semantics. Is x/y website counter?
Than rebasing should mean both changes are applied. Changing your credit
card number? Than it probably means the last should win. Or maybe fail in
the light of conflicts.

So telling how we solved it at Mendix is kind of irrelevant, because we are
not operating in the same domain. But what we do is have meta information
on every property and collection, that allows us to set conflict
resolutions, e.g; is last winner ok, or should it cause conflict? And for
collections: is ordering important, or not? As with non-important ordering
concurrent adds are fine, just apply them in any order. Etc. etc. For
further research, I suggest to google on "Operational Transformation", its
a more advanced solution that might take you further.

**Comment by eshvedai** [comment]
right, I got the idea, cheers mate 🍺
