### ISSUE TITLE
"Cannot perform 'get' on a proxy that has been revoked" only in dev

### ISSUE THREAD

**Issue by steida** [immerjs/immer#430]
## 🐛 Bug Report

I have classic reducer composition when one reducer calls another. I checked https://github.com/immerjs/immer/issues/100 and I don't think I do:

> So if you get this error, you either are calling an async process from a producer, or you are storing references to the draft somewhere

When I `setAutoFreeze(false);`, it works.

## To Reproduce

Steps to reproduce the behavior: It's hard because it worked until it stopped. The workaround is to disable autoFreeze.

## Expected behavior

Reducer composition should work when `setAutoFreeze(true);`

**Comment by mweststrate** [comment]
Please provide a minimal reproduction, without that we can't do anything.

**Comment by steida** [comment]
I know, sorry about that. I needed workaround and maybe it will help someone else.

**Comment by steida** [comment]
The more I use Immer the more I feel it's like Object.observe, which was deprecated because it was so brittle regarding nested observing. 

Now I have race conditions slightly depending on setAutoFreeze. Maybe it's because I am using YuzuJS/setImmediate. I don't know. I will try to extract a minimal reproduction soon.

**Comment by steida** [comment]
The more I use Immer the more I feel it's like Object.observe, which was deprecated because it was so brittle regarding nested observing. It's not obvious where I am making a mistake, and it's very hard to debug via console.log.

Now I have race conditions slightly depending on setAutoFreeze. Maybe it's because I am using YuzuJS/setImmediate. I don't know. 

Maybe I should write a blog post "You Might Not Need Immer"

https://twitter.com/estejs/status/1178447324781191173

**Comment by mweststrate** [comment]
Immer is designed for temporarily, local mutation. If your logic requires things like setImmediate or reaching out to complex api's you probably left the scope of what immer was designed to do. If you need mutability over time, you don't need immer, you need mutable objects. Using long lived drafts is I think just mutability in disguise. 

If your reducers have side effects in which they share references to the state beyond the run time of the reducer function; you can't use immer, as these drafts are going to disappear

**Comment by steida** [comment]
In other words, Immer producers are not composable because they leak mutability.

**Comment by mweststrate** [comment]
Over a year ago there were a couple of bugs in that area but those has been
ironed out.

Since then I think you're the first one bringing this up despite thousands
of devs using this. So I can't really jump to such conclusion yet as it
seems to me so far, without any code but just abstract statements being
discussed, that it is more likely that there is an expectation mismatch
than that there is an actual problem.

This might of course be an omission in the documentation, in which case a
PR is welcome. But so far I simply have a hard time wrapping my head around
the actual problem as there is so far zero code in this issue, and I think
further discussion or jumping to conclusions is fruitless without first
providing a concise example of the problematic behavior.

Op ma 30 sep. 2019 22:26 schreef Daniel Steigerwald <
notifications@github.com>:

**Comment by steida** [comment]
I understand and sorry for FUD. Immer is a brilliant piece of work. It's my fault I did not provide a failing example. It's hard to extract a race condition bug, which is not an excuse of course. It's also very possible I have special conditions or I made a bug. Anyway, thank you for your patience.

**Comment by steida** [comment]
So I refactored a lot of code using `fp-ts` instead of Immer, and weird race condition bug is over. Maybe it was setImmediate, who knows. The code is naturally composable and `console.log`. Good times.
