### ISSUE TITLE
Safe push for undefined attributes, safe array seting in immer

### ISSUE THREAD

**Issue by nicolas-rodriguez-globant** [immerjs/immer#446]
## 🚀 Feature Proposal

It would be great that the array methods can be used in safe mode, at the case that the array property than you try modify is undefined.

## Motivation

I'm using a dinamic object that it can contain dinamyc attributes then I need do an undefined check before use an array method `push`.

## Example

```js
// filter: {}
// filterValue: 'done'
// filterBy: 'status'
const newFilter = produce(filter, filterDraft => {
  if (!filterDraft[filterBy]) {
    filterDraft[filterBy] = [filterValue];
  } else {
    filterDraft[filterBy].push(filterValue);
  }
});
```

immer can be enable a safe use of undefined array atributes

```js
// filter: {}
// filterValue: 'done'
// filterBy: 'status'
const newFilter = produce(filter, filterDraft => {
    filterDraft[filterBy].push(filterValue);
});
// newFilter ->  { status: ['done'] }
```

**Comment by mweststrate** [comment]
Like with the elvis operator, optional chaining etc, this could all be implemented by Immer because it has proxies. The same thing could also be implemented in userland. Because, well, it has proxies :). In other words, we consider anything that improves the language beyond the scope of the language itself out of scope for this library. 

I think in general these kind of improvements should be proposed to TC39, or as babel transformation, as they don't have much to do with immer specifically, and are useful outside that.

A simple utility function could improve this code as well, or something like this also makes it shorter `(filterDraft[filterBy] || filterDraft[filterBy] =[]).push(filterValue)`

**Comment by mweststrate** [comment]
I think btw that the nevernull package can be achieved to do the above 🤔

Op ma 21 okt. 2019 22:21 schreef nicolas-rodriguez-globant <
notifications@github.com>:

**Comment by nicolas-rodriguez-globant** [comment]
Great, thank you!
