### ISSUE TITLE
Q: Detect if draft has changes to be commited before finishDraft

### ISSUE THREAD

**Issue by kilianc** [immerjs/immer#455]
Is there a way to tell if a draft is in a "dirty" state?

**Comment by kilianc** [comment]
@mweststrate I am trying to experiment passing out a draft of the global state to my render tree along with actions bound to these subtrees, let's say `updateUser({ name: 'Paul' })` calls a commit function internally that calls `finishDraft`. If `newState` and `oldState` are unchanged `setState` will be a no-op and I won't have the chance of recreating a new draft while the old draft is closed.

**Comment by mweststrate** [comment]
But why do you want to call setState if it didn't change anyway?

Op do 31 okt. 2019 16:58 schreef Kilian Ciuffolo <notifications@github.com>:

**Comment by kilianc** [comment]
@mweststrate I don't want to, that's the point.

**Comment by mweststrate** [comment]
why forcefully increase the version then? If you finish first, you could
increase the version only if the state actually changed.

**Comment by kilianc** [comment]
```js
function useGlobalState(init) {
  const [state, setState] = useState(init)
  const draftState = createDraft(state)

  const commit = () => {
    const newState = finishDraft(draftState)
    if (newState !== draftState) setState(newState)
  }

  return [draftState, commit]
}
```

This will result in a "draft already closed" error if I call `commit` without changing anything and then call it again.

**Comment by mweststrate** [comment]
I think the pattern you are using above is a very dangerous one, it is recommended to not hand out drafts left and right and have components hold on to it over time. In that case you could just use well use mutable objects int he first place and skip immer entirely :) Using drafts and immutable states now just increases complexity: you need to make sure you propage the latest draft with the latest state, and as soon as any component bails on with whatever optimisation that avoids propagating state, you get into a mess because those things will have an old draft.

It basically relates to the principles outlined here: https://egghead.io/lessons/react-write-asynchronous-producers-in-immer-and-why-you-shouldn-t
