### ISSUE TITLE
Typescript generics seems broken even with explicit drafts

### ISSUE THREAD

**Issue by FredyC** [immerjs/immer#456]
## 🐛 Bug Report

I am well aware there has been a couple of generics related issues, I tried to apply the solution from https://github.com/immerjs/immer/issues/356#issuecomment-487912575 but it doesn't seem to work.

The only way I was able to figure is typecasting to `unknown`, but it feels it kinda beats the purpose.

## To Reproduce

[Playground link](https://www.typescriptlang.org/play/index.html#code/JYWwDg9gTgLgBGKEAmBXAxgUwDRwN5wAiUAhgGbwC+cZSIcA5KCJlAwLABQoks+cqAM6YAkiBZQ41WhHoMhmALTNWHTlxgBPMJjgBlGCRiYAPABVCEdAD44AXnxc4cZEZIAuOBatwAPnAA7VAAbYKc4YIgSZGAAgHNPACMICGDMEgCuSi4uMlQA9BhgCACBYQBFVFZNS3RzWrhMAA9jAORBOAAlTHRoZBNBGChYuNwMzWtrAAoASkdOZ16AwbgAbUGjHAEwV2MDTYBdezLRcVYTfeN6q0mpvHDnXY9AkODsB4iomPjPIarwygzHILba7TCXTBTKbIUgUTwQ642OZ2Wz3EGPWEwAB0T2OZBIAGtMIQ3LMAUD1CDECgMJCNsZcNDMfDDFdvEj7KiPjDyNjcQ58USSYYySDAcDnAB6SVwGAAC2AHQA7tACYJcIlUPBgPAyJhMMEOgArITwJVIeLhaloLBTelbHkUTnzZwY3k4tx4wnE0lzEgdfIEgIQJWlf1ETGI6zkrLArQ6LwAVWEkgcaOcARILE8g2GlpBmBAJGAwRzQxGscpeQKRRKNG9wpIs08ZmTrBdcCgmBgqCgpXTrsz2cYACkIHKAgx3ujGkWS54GEbxwEAAJy2SYNTObKcShAA)

## Expected behavior

I would be expecting something that simple would work, but I am either missing something obvious or it's not really possible to use generics with TypeScript without hassle.

It is curious why in the case of `useImmer` the error is much more head-scratching, but I can only assume it's coming down from `produce` itself having a problem.

## Environment

- **Immer version:** 5.0.0

**Comment by mweststrate** [comment]
The error generated by TypeScript is entirely correct, as `TUser` is a concrete type, but `TDoc isn't. So as far as TypeScript is concerned, `TDoc` could just as well be `{ foo: "string", bar: "string}`, which is completely unrelated to `TUser`, and `TUser` would not be assignable to that. Probably you want to either set a better constraint here (e.g. `TDoc extends TUser` instead of some random `Record`).

I think this issue is further not related to Immer at all. But what you are probably looking for, is that your hook accepts _any_ kind of Record, rather than some very specific type of Record. So the following does I think what you want to achieve, and is valid, as `TUser` is a valid `Record`:

```typescript

function useQueryDoc() {
  const [state, updateState] = useImmer<Record<string, any>>({
    data: null,
    loading: true
  })

  updateState((draft: Record<string, any>) => {
    draft.data = fakeData()
  })

  produce(state, (draft: Record<string, any>) => {
    draft.data = fakeData()
  })

  // this works, but it feels just wrong
  produce(state, draft => {
    draft.data = fakeData() as unknown as Draft<TDoc>
  })
}
```
