### ISSUE TITLE
When finalizing drafts, perform an shallow equal check and reuse previous instance if possible

### ISSUE THREAD

**Issue by lake2** [immerjs/immer#491]
## 🐛 Bug Report

```
import produce from "immer";

const a = { highlight: true };


const next1 = produce(a, draft => {
  draft.highlight = false;
  draft.highlight = true;
});

console.log(a === next1);// false, should be true
```
CodeSandbox  https://codesandbox.io/s/todos-useapi-and-immer-cof4w

**Comment by mweststrate** [comment]
This is working as intended. Immer will only detect and bail out if the draft is not even temporarily modified, that is, 

```javascript
const a = { highlight: true };

const next1 = produce(a, draft => {
  draft.highlight = true;
});

console.log(a === next1) // true
```

The reason that it works this way, is that otherwise would always need to do quite expensive shallow checks for every modified node, which sounds like something that can have quite some performance impact, although it will also have an positive impact on other places. 

That is the reason this case is not optimized. That being side, I'm open to the idea of always doing this shallow check and experimenting if this has a net positive impact for applications in practice.

**Comment by lake2** [comment]
I found the behavior when I use pure component in reacting.
In pure component, react will execute a shallow compare between two states, this behavior will cause an unexpected render of pure component, though I can pass my own compare function to stop this render.
Thanks for your work.
