### ISSUE TITLE
Proposal: Adding entries for features support

### ISSUE THREAD

**Issue by oriSomething** [immerjs/immer#548]
## 🚀 Feature Proposal

Adding entries to auto enable features. Example:

```js
// This
import produce from "immer/enable-map-set";
// Instead  of this
import produce, { enableMapSet } from "immer";
enableMapSet();

// More enable features entries
import produce from "immer/enable-all";
import produce from "immer/enable-patches";
```

#### The cons are:

- Harder to produce a bundle
- It's easier to add feature, hard to remove

## Motivation

- Making easier to manage a project where some parts might needed more features from immer, without finding it on runtime by mistake
- Making easier not to rely on execution order

## Can this be sovled in user-land code?

Creating an entry inside an app that does it

## Example

In  **Feature Proposal**

**Comment by patrick-entinux** [comment]
I was considering the same idea. It would be similar pattern to Node.js require helpers, like ts-node, for example:
```
require('ts-node').register();
require('ts-node/register');
```
https://www.npmjs.com/package/ts-node#programmatic

In my Node application I'm going to try something like the following, create new file exporting immer with the plugin enabled:

```typescript
// /app/util/immer-with-plugins.ts
import { enableAllPlugins } from 'immer';
enableAllPlugins();
export * from 'immer';
```

Then, in the file that uses immer, import from the file above instead of immer directly:

```typescript
import { produceWithPatches } from '../app/util/immer-with-plugins';

produceWithPatches(/* ... */)
```

But if this feature came from immer plugin directly, it would be really easy to use find and replace, and not worry about relative paths.

**Comment by mweststrate** [comment]
This would have been an alternative way to implement this. But since the current setup has been already released, and this would be a breaking change, and I don't see any good arguments to change it without aesthetics, this won't be updated.

Pro:
* looks nicer?
* smaller files without applying tree-shaking (but I that case you probably don't care about size anyway, soo booyah?)

Con:
* will result in different setups for UMD builds
* Very limited flexibility in dealing with different kinds of entry points in package.json (most fields support only one entry point)
* In my experience tooling often deals badly with multiple entry points packages (for example bundlephobia probably won't know about the different entry points and can't show them)
* Needs ugly wrappers in the root to redir to right files, possible for every module type we want to support (esm, cjs, what ever there might be in the future)

**Comment by gonzofish** [comment]
An argument I can see is if you have to support IE11 and modern browsers and only want to load the `enableES5` code when a user needs it, if possible.

Totally understand if you can't though. Thanks for the great library!
