### ISSUE TITLE
What if I want to change filed on __proto__ instead of current instance?

### ISSUE THREAD

**Issue by lovetingyuan** [immerjs/immer#579]
## 🙋‍♂ Question

```javascript
const immer = require('immer')
const baseState = Object.create({base: 0, [immer.immerable]: true})
baseState.child = 1
baseState[immer.immerable] = true

const nextState = immer.produce(baseState, state => {
    state.base = 2
})

console.log(nextState, nextState.__proto__)
/*
the output:
{base: 2, child: 1}, {base: 0}
*/
```
immer create `base` property on current object with the same name which overrides the same  property on proto. What if I do not want to override? 
I want the nextState could be: 
```javascript
{child: 1, __proto__: { base: 2 }  } 
```

**Comment by mweststrate** [comment]
Assignements to instances in JavaScript never change the prototype, they
shadow fields on the instance instead, so this is the correct behavior.
(Imagine what would happen otherwise if you used that prototype twice, you
would be changing all instances!)

If you really want to change the prototype you have to assign to the
prototype directly, not the instance. Which is a really bad and confusing
idea imho 😅

Op vr 17 apr. 2020 05:16 schreef tingyuan <notifications@github.com>:

**Comment by lovetingyuan** [comment]
Yes, modify prototype is indeed a bad idea. Thanks for your answer.
