### ISSUE TITLE
Immer does not return a draft version for unchanged data

### ISSUE THREAD

**Issue by Kiran554** [immerjs/immer#618]
## 🐛 Bug Report

```
immer.enableAllPlugins();

const baseState = [
    {
        todo: "Learn typescript",
        done: true
    },
    {
        todo: "Try immer",
        done: false
    }
]

const nextState = produce(baseState, draftState => {
    // Do nothing, just want a copy of baseState
   // Doc says by default produce returns `draftState`, so I care not to return again.
})


console.log(baseState === nextState)  // Returns true, but expected false.


const nextState = produce(baseState, draftState => {
    // Do nothing, just want a copy of baseState
   return draftState;
   // Even returning the `draftState` made no difference.
})

console.log(baseState === nextState)  // Returns true, but expected false.


const nextState = produce(baseState, draftState => {
     draftState.push({todo: "Tweet about it"})
})

console.log(baseState === nextState)  // Returns false, expected result.

```

## Link to repro
N/A

## To Reproduce

Run the above code and see the o/p of first and second console.log. 

## Observed behavior

Both logs are returning `true`

## Expected behavior

But expected to return `false`

## Environment

Used latest version, Ran using npm runkit.

**Comment by mweststrate** [comment]
This is working as intended. Immer doesn't copy anything that isn't changed
because that is not needed if the returned data is treated immutable. If
you need a copy because you are going to change it, you aren't working on
immutable principles and there is no need to use Immer in the first place
and you should use a deepClone utility instead

Op vr 12 jun. 2020 23:37 schreef Kiran A <notifications@github.com>:

**Comment by Kiran554** [comment]
Makes sense. Because if the data is not changed, then there's no point to create a copy, which breaks the principle of immutability. 

Thanks for confirming.
