### ISSUE TITLE
Irrelevant banner on site

### ISSUE THREAD

**Issue by lLenn** [immerjs/immer#656]
So when's the BLM banner going to go down?
There's been like +30 murders, looting, rioting, racketeering and other heinous crimes under the banner of BLM.
This is no longer a simple statement showing sympathy for a troubled community.
The BLM leadership has openly approved the rioting and called it "reparations".
BLM has also gotten their demands met, but continue to raise havoc across mutliple states.
Instead of working toward bettering the communities it has been tearing them down.
This is an open-source technology project.
To put this message on here is to work outside of the scope of your expertise.
I'm not here to have your opinion about social issues.
I quite frankly don't trust you to have a well researched one.
I respect you for the programming you do, not your activism.

**Comment by mweststrate** [comment]
> So when's the BLM banner going to go down?

No idea, didn't give any thought to a planning

> There's been like +30 murders, looting, rioting, racketeering and other heinous crimes under the banner of BLM.
This is no longer a simple statement showing sympathy for a troubled community.

It's a quite simple 3 word, binary value proposition, with which you either agree, or you don't. But there is no reason to read more into it than that, it is not a recommendation of any specific party, organisation or even course of action. 

> This is an open-source technology project.
To put this message on here is to work outside of the scope of your expertise.
I'm not here to have your opinion about social issues.

The contents of the ads running on the website is outside my expertise as well, and you are not here to see those either. Yet I think I'm fully entitled to show them. Especially when you're not sponsoring this project financially. You're allowed to use my work for free, having the decency to hear my opinion, not ban ads, etc, is the least you can do. 

> I'm not here to have your opinion about social issues.

In that case I'm puzzled why you are sharing yours, including arguments and your reading of the situation. This issue is now irrelevant by your own definition ;)

> I quite frankly don't trust you to have a well researched one.
I respect you for the programming you do, not your activism.

That's completely fine.

**Comment by lLenn** [comment]
> It's a quite simple 3 word, binary value proposition, with which you either agree, or you don't. But there is no reason to read more into it than that, it is not a recommendation of any specific party, organisation or even course of action.

This is a very dishonest statement. I keep hearing it and I'm quite sick of it. You absolutely can and the leaders of BLM definitely have more in mind than just those 3 words. If you want to be technical, your statement is dehumanizing as it suggests that the only way to correctly interpret the statement is without any emotional attachment. Humans are emotional creatures firstly and rational secondly. Without any emotional significance the statement also has no meaning as it is a value statement.

> The contents of the ads running on the website is outside my expertise as well, and you are not here to see those either.

That's a good point and I've added it to my ad-blocker. Still, ads aren't generally politically loaded and even then you can tell google not to show such ads again.

> In that case I'm puzzled why you are sharing yours, including arguments and your reading of the situation. This issue is now irrelevant by your own definition ;)

It's irrelevant because it's political content on a technology site, not because you're sharing it. You can do that on twitter.
