### ISSUE TITLE
immer won't generate patches when giving a non-draftable value

### ISSUE THREAD

**Issue by DanSnow** [immerjs/immer#675]
## 🐛 Bug Report

I'm not sure is this a bug or intent behavior. Please see the follow code example:

```javascript
enablePatches(true)

produce('foo', () => 'bar', (patches, inversePatches) => {
  // this function is even not called
  console.log(patches, inversePatches)
})
```

I'm using the patches to create a undo/redo feature, and I expect that immer could give patches for any value (only primitive value and simple object, no class).

Because only the replace operator is valid for non-draftable value. Is it possible to add a check at here when 
`patchListener` is given and call it with the replace patch?

https://github.com/immerjs/immer/blob/master/src/core/immerClass.ts#L119

## Observed behavior

immer won't call the `patchListener` when giving a non-draftable value.

## Expected behavior

immer give the patches.

## Environment

- **Immer version:** `7.0.9`
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Primitive values are not patchable, so I'm not sure what the patch here even should be? Please do specify expected behavior in more detail :) In general it sounds that you are calling `produce` on the wrong object, and that you should call it only on the root of your state, rather than at specific leaf nodes of your tree.

**Comment by mweststrate** [comment]
Closing for lack of relevant info
