### ISSUE TITLE
How to detect if autoFreeze is on?

### ISSUE THREAD

**Issue by Noitidart** [immerjs/immer#757]
In dev, there is one place where if the object is frozen, some features won't work (like lottie json source). Is it possible to: detect if autoFreeze state, if on then disable it, then do my modification to the json, then retrurn autoFreeze to original state.

Or is there another way to `produce` without autoFreeze if its on?

**Comment by mweststrate** [comment]
When you have a problem, please state the problem rather than the solution so that we can understand the actual problem :). Objects can't be unfrozen nor should you want to, as it kills all assumptions. If you want to associate more data with an already frozen object, I recommend to use weakmaps instead. For more follow up questions, please provide a snippet of the problem you are trying to solve

**Comment by Noitidart** [comment]
Oh thank you so much for the reply still even though I was vague. The issue is I'm using `<LottieView>` in react-native, and that viewer seems to mutate the source. So when I freeze the source object the view doesn't load.

I have to modify the source object to give it custom colors:

```
import LottieView from 'lottie-react-native';


....

const coloredSource = colorizeLottie(source);
return (
      <LottieView
        source={coloredSource}
      />
)
...

function colorizeSource(json, colors) {
   return produce(json, draft => { ... } );
}

```

Thanks very much for the amazing work and taking time out to respond!

**Comment by mweststrate** [comment]
That sounds like an issue that should be taken up with lottie?

**Comment by Noitidart** [comment]
Oo you're right I'll talk to them. Thank you!
