### ISSUE TITLE
IProduceWithPatches returns Immutable<Base> while IProduce is not

### ISSUE THREAD

**Issue by marc-polizzi** [immerjs/immer#777]
## 🐛 Bug Report

IProduceWithPatches returns Immutable<Base> while IProduce is not:

In our Typescript code the following line requires nextState to be Immutable:

```
    const [nextState, redoPatches, undoPatches] = produceWithPatches(state, draft => {
```

while that one not:

```
    const nextState = produce(state, draft => {

```
As a workaround we're casting to <Base> the returned state of produceWithPatches.

## Expected behavior

I would expect produceWithPatches() following the same constraint as produce() 

## Environment

Immer 9.0.1
Typescript: 4.2.3

Thanks for your hard work.

**Comment by mweststrate** [comment]
Did you try to type either the `draft` or `state` argument explicitly with the mutable type? Otherwise please provide a minimal sandbox to take a closer look.

**Comment by somebody32** [comment]
@mweststrate here is a sandbox so that you can take a look: https://codesandbox.io/s/immer-immutabe-type-mismatch-wvlid

As you can see, `newData` can't be reassigned when using `produceWithPatches` because of the Immutability. If it is more convenient for you, I can open a new issue, but I believe it would be easier just to reopen this one
