### ISSUE TITLE
attempted to get private field on non-instance

### ISSUE THREAD

**Issue by Laurian** [immerjs/immer#828]
## 🐛 Bug Report

Method access to private fields is broken once object is mutated. 

## Link to repro

Run `node index.js` in the terminal of https://stackblitz.com/edit/node-vgauyr?file=index.js

## To Reproduce

1. create an `immerable` class with a private field
2. make that field visible for `JSON.stringify`

```
class Foo {
  [immerable] = true;
  foo = 1;
  #bar = 2;

  toJSON() {
    return {
      foo: this.foo,
      bar: this.#bar
    };
  }
}
```
3. mutate an instance of the object with `produce`
4. try to serialise with `JSON.stringify`

## Observed behavior

Error thrown:
- Browser: TypeError: attempted to get private field on non-instance
- Node: TypeError: Cannot read private member #bar from an object whose class did not declare it

## Expected behavior

`JSON.serialise` which calls `toJSON()` should work without errors.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Immer doesnt support JS privates as they aren't visible to the draft
object, since they are private

**Comment by Laurian** [comment]
I don't want to read or mutate private fields on the draft; I'm puzzled by the result of `produce` being the same class as the original object is actually missing the private field?

**Comment by mweststrate** [comment]
What result would you expect? 1) `test2` ending up with the value that is the same as `test1`, 2) or the same value as initialised by `Foo`'s constructor, or 3) `undefined`? 

1) is would probably be what most would expect / hope for, but is not possible as a generic cloning utility will not be able to read the private. 
2) vs 3) depends on whether the default value is stored on the prototype or set by the constructor (Object.create, the generic way to clone, doesn't run constructors). Which in turn depends on your transpilation settings. TS / babel used to initialise fields as part of the constructor, and this legacy behavior seems to be what is happening in stackblitz (since Object.create(Foo) leaves boths fields `undefined`). But that is not what got standardised by ECMA script

For reference a repro without produce: https://stackblitz.com/edit/node-gu8j1y?file=index.js. Underlying issue might be prototype method ending up on the instance so that might need addressing. But beyond that private fields + cloning sounds like a recipe for confusion in any case for above reasons.

**Comment by Laurian** [comment]
I would expect (1), anyway I understand the limitations, I won't use private fields then.
