### ISSUE TITLE
array "-" patches are inserting at beginning instead of appending to the end

### ISSUE THREAD

**Issue by bradedelman** [immerjs/immer#897]
const state0 = {a: []};
const state1 = applyPatches(state0, [{op: "add", path: ["a","-"], value: 1}]);
const state2 = applyPatches(state1, [{op: "add", path: ["a","-"], value: 2}]);
const state3 = applyPatches(state2, [{op: "add", path: ["a","-"], value: 3}]);
console.log(state3);
  
per the JSON patch spec should produce state3 as:
{ a: [ 1, 2, 3 ] }

however, Immer produces state3 as:
{ a: [ 3, 2, 1 ] }

this is wrong.  Immer is inserting at beginning instead of appending to the end

**Comment by mweststrate** [comment]
Some changes were made in this area recently, which version of Immer are you using?

**Comment by bradedelman** [comment]
version "9.0.7"

**Comment by mweststrate** [comment]
I just tried the above example on the lasted version of Immer, but it does yield `[1,2,3]` in our unit test setup, would you mind creating a sandbox reproduction (see the issue template), or PR a unit test that demonstrates the problem?

**Comment by bradedelman** [comment]
to say can't reproduce without at least trying 9.0.7 feels a bit disingenuous.

**Comment by bradedelman** [comment]
also, looks like you added the test case already? thank you for that.

**Comment by mweststrate** [comment]
> by unit test, what do you need more than the code in the example? that seems like the test. you need it in a specific way? also, did you try with version 9.0.7? I should try with the newer version, but I suspect you will repro with 9.0.7.

Given the unit test, it means that it is not reproducible against the latest version (9.0.12) on a standard environment. Whether it reproduces against 9.0.7 doesn't matter, since we aren't going to re-release 9.0.7; the problem is either not present anymore in a later version, so you can just upgrade. Or the problem is still present in a later version, but the problem only occurs in a specific environment (e.g. certain browser, in combination with another lib, something like that), in which case we'll need a reproducible reproduction as otherwise we can't investigate; since the problem doesn't occur on a standard V8 node JS.
