### ISSUE TITLE
Edge Runtime support

### ISSUE THREAD

**Issue by rpavlovs** [immerjs/immer#956]
## 🙋‍♂ Question

I'm trying to use `immer` in Vercel's Edge Functions (not directly but as a `redux-toolkit` dependency)
and getting the following error:
```
./node_modules/immer/dist/immer.esm.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Middleware middleware
```

Upon further look, it seems that Immer is using `new Function` call, [which is not allowed in Edge Runtime](https://nextjs.org/docs/advanced-features/react-18/switchable-runtime)

Is it possible to make Immer work in this runtime?

## Environment
- **Immer version: 9.0.15**

**Comment by mweststrate** [comment]
Afaik we don't use `new Function`, couldn't find it in either source or compiled version, so probably something else is wrong. https://unpkg.com/immer@9.0.15/dist/immer.esm.js

**Comment by kevinold** [comment]
@mweststrate Here is a repo with a reproduction: https://github.com/revmischa/amplify-ssr-next-middleware-repro

Note that this repo is specifically pointing out the lack of Edge Runtime support for AWS Amplify and it's libraries (as filed here https://github.com/aws-amplify/amplify-js/issues/9145), but since `immer` is a dependencies of one or more libraries Amplify or the aws-sdk depends on, the error reported originally for this issue appears in the details of the README for the reproduction.

![Screen Shot 2022-10-28 at 11 15 45 AM](https://user-images.githubusercontent.com/21967/198685034-ccba888d-4fd4-43f5-a3da-b47b92a4ea08.png)



A minimum reproduction would just be to include immer in the `middleware.js` of a Next.js project.

**Comment by mweststrate** [comment]
Hey @kevinold, I'm not sure how to address the above issue, as, as you might check the referred immer.esm.js file, there is no `eval`, dynamic function construction or WebAssembly in there. 

The only thing I can think of that errors, is that Immer by default uses Proxies, which are kinda dynamic. That can be disabled however by calling `enableES5()` at the start of your application and before first Immer usage: https://immerjs.github.io/immer/installation#pick-your-immer-version. Otherwise it would need a deeper investigation why your Edge runtime *thinks* there is dynamic code evaluation in there.

**Comment by mweststrate** [comment]
FWIW, it seems the error can be suppressed with this config: https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis. If Immer still works after that, it might be a false positive.
